# Generated by Django 4.2.7 on 2023-12-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0018_order_is_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('SH', 'Shipped'), ('CM', 'Completed')], default='PD', max_length=2),
        ),
    ]
