# Generated by Django 4.2.7 on 2023-12-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0019_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PD', 'Pending'), ('SH', 'Shipped'), ('CM', 'Completed'), ('CN', 'Cancelled')], default='PD', max_length=2),
        ),
    ]
